language: node_js
addons:
  firefox: "45.0"
node_js:
  - '6'
sudo: false
cache:
  directories:
    - node_modules
services:
before_install:
  - npm --version
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start